# Generated by Django 4.2.4 on 2023-08-25 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='added_by',
            field=models.ForeignKey(default='0adec873-f6ce-4220-8a80-be3eb5b49274', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
