# Generated by Django 4.2.4 on 2023-08-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resource',
        ),
    ]
